### ISSUE TITLE
Feature Request: Support custom YAML anchors

### ISSUE THREAD

**Issue by jayhawk-commits** [jayhawk-commits/rocPRIM#1]
We’d like to request support for YAML anchors and aliases in config files.

**Example:**
```
defaults: &defaults
  timeout: 30
  retries: 3

build: 
  <<: *defaults
  image: ubuntu-latest
```

This would simplify reuse of config blocks.
Thanks! 🙏
